import{PDFDocument,degrees}from'pdf-lib';
import{getDocument,GlobalWorkerOptions}from'pdfjs-dist';
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import type{PdfEngine,ImportedDocument}from'./PdfEngine';import type{WorkspaceState}from'../domain/workspace';import{AppError}from'../errors/AppError';import{newId}from'../lib/ids';
GlobalWorkerOptions.workerSrc=pdfWorkerUrl;
const accepted=new Set(['application/pdf','image/jpeg','image/png','image/webp']);
const canvasBlob=(c:HTMLCanvasElement,type='image/png')=>new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Canvas encoding failed')),type));
async function imageSize(bytes:ArrayBuffer,mime:string){const blob=new Blob([bytes],{type:mime});const bitmap=await createImageBitmap(blob);const size={width:bitmap.width,height:bitmap.height};bitmap.close();return size}
export class BrowserPdfEngine implements PdfEngine{
 async importFile(file:File):Promise<ImportedDocument>{if(!accepted.has(file.type))throw new AppError('unsupported-file','This file type is not supported yet.');const bytes=await file.arrayBuffer();if(file.type!=='application/pdf'){const size=await imageSize(bytes,file.type);return{id:newId(),fileName:file.name,mimeType:file.type,kind:'image',bytes,pages:[{sourcePageIndex:0,...size}]}}try{const pdf=await getDocument({data:bytes.slice(0)}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const v=page.getViewport({scale:1});pages.push({sourcePageIndex:i-1,width:v.width,height:v.height})}return{id:newId(),fileName:file.name,mimeType:file.type,kind:'pdf',bytes,pages}}catch(e){const msg=String((e as Error)?.message??e);if(/password/i.test(msg))throw new AppError('password-protected','This PDF is password-protected. Password-protected files are not supported yet.');throw new AppError('invalid-pdf','We couldn’t open this PDF.')}}
 async renderThumbnail(doc:ImportedDocument,pageIndex:number,maxWidth:number):Promise<Blob>{if(doc.kind==='image')return new Blob([doc.bytes],{type:doc.mimeType});const pdf=await getDocument({data:doc.bytes.slice(0)}).promise;const page=await pdf.getPage(pageIndex+1);const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:maxWidth/base.width});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');await page.render({canvasContext:ctx,viewport}).promise;return canvasBlob(canvas)}
 async exportWorkspace(documents:ReadonlyMap<string,ImportedDocument>,workspace:WorkspaceState):Promise<Blob>{try{const out=await PDFDocument.create();const cache=new Map<string,PDFDocument>();for(const wp of workspace.pages){const src=documents.get(wp.sourceDocumentId);if(!src)continue;if(src.kind==='pdf'){let pdf=cache.get(src.id);if(!pdf){pdf=await PDFDocument.load(src.bytes.slice(0));cache.set(src.id,pdf)}const [page]=await out.copyPages(pdf,[wp.sourcePageIndex]);page.setRotation(degrees(wp.rotation));out.addPage(page)}else{const pageInfo=src.pages[0];const page=out.addPage([pageInfo.width,pageInfo.height]);let embedded;if(src.mimeType==='image/jpeg')embedded=await out.embedJpg(src.bytes);else if(src.mimeType==='image/png')embedded=await out.embedPng(src.bytes);else{const blob=new Blob([src.bytes],{type:src.mimeType});const bitmap=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d')!.drawImage(bitmap,0,0);bitmap.close();const png=await canvasBlob(canvas);embedded=await out.embedPng(await png.arrayBuffer())}page.drawImage(embedded,{x:0,y:0,width:pageInfo.width,height:pageInfo.height});page.setRotation(degrees(wp.rotation))}}const bytes=await out.save();return new Blob([bytes],{type:'application/pdf'})}catch(e){throw new AppError('export-failed','We couldn’t create the PDF. Your workspace is still here.')}}
}
